services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: godo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_app_container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: godo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
